[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/aoc/aoc.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
paste = "1.0.15"
